# Generates lib/l10n/app_translations.dart from aligned translation packs.
# Run: python tool/gen_l10n.py

from pathlib import Path

KEYS = [
    "Skip",
    "Esay Tracking",
    "Tracking any device with user friendly software",
    "Save Your Time",
    "save your time by optimization of your operations",
    "Go Back",
    "Login",
    "User ID",
    "Password",
    "Forget Your Password?",
    "LOG IN",
    "Please enter User ID",
    "Invalid User Id",
    "Dashboard",
    "Fleet Status",
    "Engine Hours",
    "Travel Distance (in KM)",
    "Hours",
    "KM",
    "Running",
    "Idle",
    "Stopped",
    "Expired",
    "InActive",
    "Inactive",
    "No Data",
    "Objects",
    "Today's Fuel Rate",
    "Diesel",
    "Petrol",
    "Maintenance Reminder",
    "Pending",
    "Overdue",
    "Expense",
    "Add Expense",
    "Quick Links",
    "E Challan",
    "Get License",
    "Recharge Fastag",
    "Check Tolls",
    "Buy Insurance",
    "Tow Service",
    "Search state",
    "No state found",
    "Vehicle List",
    "Search Vehicle",
    "All vehicles",
    "No Vehicle Found",
    "Reports",
    "Ignition Report",
    "AC Report",
    "Trip Report",
    "Stoppage Report",
    "Summary Report",
    "Daily Report",
    "Speed Report",
    "Geofence Report",
    "From Date",
    "End Date",
    "Export",
    "Share",
    "Settings",
    "Account",
    "Name",
    "Mobile Number",
    "App Settings",
    "Live Support",
    "Downloaded Reports",
    "Sign Out",
    "General Settings",
    "Change Password",
    "Configure Alerts",
    "Drivers",
    "Reminders",
    "Groups",
    "Geofences",
    "Share app",
    "Old Password*",
    "Confirm Password*",
    "CANCEL",
    "OK",
    "Apply",
    "Search",
    "Search language",
    "No language found",
    "Choose Language",
    "Choose Theme",
    "Choose Vehicle icon",
    "Light Theme",
    "Dark Theme",
    "Aurora Theme",
    "Hacking Theme",
    "Vehicle Icon Size",
    "Time Format",
    "Speedo Meter",
    "Default Page",
    "Map Type",
    "Fuel Unit",
    "Language",
    "Speed",
    "Distance",
    "Area",
    "Voice Command",
    "Currency",
    "Live Page Trail",
    "Show History on Live",
    "Filter History Fluctuation",
    "Farm Calculation",
    "Notification",
    "Fuel Reading",
    "History Route Color",
    "App Color",
    "Relay Password",
    "Zoom Level",
    "Small",
    "Medium",
    "Large",
    "12 Hours",
    "24 Hours",
    "Analog",
    "Digital",
    "Live Page",
    "Map Page",
    "Reports Page",
    "Normal",
    "Satellite",
    "Hybrid",
    "Liter",
    "Gallon",
    "kmh",
    "mph",
    "km",
    "mile",
    "Hectare",
    "Acre",
    "ON",
    "OFF",
    "Device",
    "Sensor",
    "Default Color",
    "Blue",
    "Green",
    "Red",
    "Pink",
    "Set Password",
    "Remove Password",
    "Stop duration",
    "Idle duration",
    "Stop count",
    "Fuel cost",
    "Engine work",
    "Fuel consumption",
    "Odometer",
    "Engine hours",
    "Location",
    "Limit",
    "Actual",
    "Duration",
    "Geofence",
    "Max Speed",
    "Circular",
    "Polygon",
    "From Gallery",
    "From camera",
    "Enter Message",
    "Add new group",
    "Update group",
    "Search User",
    "Search vehicle...",
    "Please select a vehicle first",
    "Please enter name and unique id",
    "Please fill all fields",
    "Please enter fence name",
    "Please add a location",
    "Please enter group name",
    "Please select reminder type",
    "Please enter odometer values",
    "Please select a vehicle",
    "Please select ticket type",
    "Please enter message",
    "Ticket raised successfully",
    "Please enable location services",
    "Could not get current location",
    "Could not open phone app",
    "Opening email...",
    "Export to Excel",
    "Export to PDF",
    "coming soon",
    "Could not open {name}",
    "{title} coming soon",
    "Exporting {title} to {label}...",
    "Gallery Error: {error}",
    "Image Error: {error}",
    "Server 1",
    "Server 2",
    "Server 3",
]

# Aligned with KEYS. Import packs from l10n_packs.py
from l10n_packs import PACKS  # noqa: E402


def dart_str(value: str) -> str:
    escaped = (
        value.replace("\\", "\\\\")
        .replace("'", "\\'")
        .replace("\n", "\\n")
        .replace("\r", "")
    )
    return f"'{escaped}'"


def main() -> None:
    n = len(KEYS)
    for code, values in PACKS.items():
        if len(values) != n:
            raise SystemExit(
                f"{code} has {len(values)} strings, expected {n}"
            )

    lines = [
        "// Generated by tool/gen_l10n.py — do not edit by hand.",
        "const List<String> _kAppL10nKeys = <String>[",
    ]
    lines.extend(f"  {dart_str(key)}," for key in KEYS)
    lines.append("];")
    lines.append("")

    for code, values in PACKS.items():
        ident = code.replace("-", "_")
        lines.append(f"const List<String> _kAppL10n_{ident} = <String>[")
        lines.extend(f"  {dart_str(value)}," for value in values)
        lines.append("];")
        lines.append("")

    lines.append("Map<String, String> _zip(List<String> values) {")
    lines.append(
        "  return Map<String, String>.fromIterables(_kAppL10nKeys, values);"
    )
    lines.append("}")
    lines.append("")
    lines.append("final Map<String, Map<String, String>> kAppTranslations =")
    lines.append("    <String, Map<String, String>>{")
    for code in PACKS:
        ident = code.replace("-", "_")
        lines.append(f"  {dart_str(code)}: _zip(_kAppL10n_{ident}),")
    lines.append("    };")
    lines.append("")

    out = Path(__file__).resolve().parents[1] / "lib" / "l10n" / "app_translations.dart"
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out} ({len(PACKS)} languages, {n} keys)")


if __name__ == "__main__":
    main()
